### ISSUE TITLE
Foreign key constraint when deleting a category that has POI

### ISSUE THREAD

**Issue by shampine** [GunnJerkens/gj-maps#22] opened 2014-08-07 20:23 UTC
Need to either:

A) Delete the category and all POI
B) Delete the category and set all POI to default

Not sure which is the best option atm.

**Comment by guitarbeard** [comment] 2016-03-02 20:27
Closing this as it seems to be a duplicate of #26

**Closed by guitarbeard** 2016-03-02 20:27 UTC
Labels: bug
